package org.wikirate4j.utils;

public enum WikirateTopic {

    ENVIRONMENT("Wikirate ESG Topics+Environment"),
    SOCIAL("Wikirate ESG Topics+Social"),
    GOVERNANCE("Wikirate ESG Topics+Governance"),
    TRANSPARENCY("Wikirate ESG Topics+Transparency"),
    HUMAN_RIGHTS("Wikirate ESG Topics+Human Rights"),
    SUSTAINABLE_SUPPLY_CHAINS("Wikirate ESG Topics+Sustainable Supply Chains"),
    HUMAN_RIGHTS_DUE_DILIGENCE("Wikirate ESG Topics+Human Rights Due Diligence"),
    LABOR_RIGHTS_AND_WORKING_CONDITIONS("Wikirate ESG Topics+Labor Rights & Working Conditions"),
    SUPPLIER_CODE_OF_CONDUCT("Wikirate ESG Topics+Supplier Code of Conduct"),
    CLIMATE_CHANGE("Wikirate ESG Topics+Climate Change"),
    GRIEVANCE_MECHANISMS("Wikirate ESG Topics+Grievance Mechanisms"),
    SUSTAINABILITY_AND_ESG_REPORTING("Wikirate ESG Topics+Sustainability & ESG Reporting"),
    SUSTAINABILITY_STRATEGY("Wikirate ESG Topics+Sustainability Strategy"),
    GREENHOUSE_GAS_GHG_EMISSIONS("Wikirate ESG Topics+Greenhouse Gas (GHG) Emissions"),
    RISK_MANAGEMENT("Wikirate ESG Topics+Risk Management"),
    DIVERSITY_EQUITY_AND_INCLUSION_DEI("Wikirate ESG Topics+Diversity, Equity & Inclusion (DEI)"),
    ENERGY("Wikirate ESG Topics+Energy"),
    WASTE("Wikirate ESG Topics+Waste"),
    SUPPLY_CHAIN_TRANSPARENCY("Wikirate ESG Topics+Supply Chain Transparency"),
    GENDER_EQUALITY("Wikirate ESG Topics+Gender Equality"),
    BIODIVERSITY("Wikirate ESG Topics+Biodiversity"),
    WATER("Wikirate ESG Topics+Water"),
    CORPORATE_GOVERNANCE("Wikirate ESG Topics+Corporate Governance"),
    SUSTAINABLE_MATERIALS("Wikirate ESG Topics+Sustainable Materials"),
    COMMUNITY_IMPACT("Wikirate ESG Topics+Community Impact"),
    WAGE_TRANSPARENCY("Wikirate ESG Topics+Wage Transparency"),
    SUPPLIER_AUDITS_AND_MONITORING("Wikirate ESG Topics+Supplier Audits & Monitoring"),
    CIRCULAR_ECONOMY("Wikirate ESG Topics+Circular Economy"),
    FREEDOM_OF_ASSOCIATION("Wikirate ESG Topics+Freedom of Association"),
    WATER_MANAGEMENT("Wikirate ESG Topics+Water Management"),
    BUSINESS_ETHICS("Wikirate ESG Topics+Business Ethics"),
    CLEAN_AND_RENEWABLE_ENERGY("Wikirate ESG Topics+Clean and Renewable Energy"),
    CLIMATE_TARGETS_AND_TRANSITION_PLANS("Wikirate ESG Topics+Climate Targets & Transition Plans"),
    ENERGY_MANAGEMENT_AND_EFFICIENCY("Wikirate ESG Topics+Energy Management & Efficiency"),
    PUBLIC_ESG_COMMITMENTS("Wikirate ESG Topics+Public ESG Commitments"),
    HEALTH_AND_SAFETY("Wikirate ESG Topics+Health & Safety"),
    SUSTAINABLE_AGRICULTURE("Wikirate ESG Topics+Sustainable Agriculture"),
    CARBON_FOOTPRINT_OF_SUPPLY_CHAIN("Wikirate ESG Topics+Carbon Footprint of Supply Chain"),
    SUPPLY_CHAIN_RISK("Wikirate ESG Topics+Supply Chain Risk"),
    CLIMATE_CHANGE_POLICY("Wikirate ESG Topics+Climate Change Policy"),
    OCCUPATIONAL_HEALTH_AND_SAFETY("Wikirate ESG Topics+Occupational Health & Safety"),
    CIRCULAR_ECONOMY_STRATEGIES("Wikirate ESG Topics+Circular Economy Strategies"),
    EDUCATION_AND_TRAINING("Wikirate ESG Topics+Education & Training"),
    STAKEHOLDER_ACCOUNTABILITY("Wikirate ESG Topics+Stakeholder Accountability"),
    WATER_CONSERVATION("Wikirate ESG Topics+Water Conservation"),
    MODERN_SLAVERY("Wikirate ESG Topics+Modern Slavery"),
    EMPLOYEE_TRAINING_AND_DEVELOPMENT("Wikirate ESG Topics+Employee Training & Development"),
    FINANCIAL_GOVERNANCE("Wikirate ESG Topics+Financial Governance"),
    MIGRANT_WORKER_PROTECTIONS("Wikirate ESG Topics+Migrant Worker Protections"),
    EMPLOYMENT_CONTRACTS("Wikirate ESG Topics+Employment Contracts"),
    RECYCLED_MATERIALS("Wikirate ESG Topics+Recycled Materials"),
    CORPORATE_GOVERNANCE_STRUCTURE("Wikirate ESG Topics+Corporate Governance Structure"),
    WASTE_MANAGEMENT_AND_DISPOSAL_PRACTICES("Wikirate ESG Topics+Waste Management & Disposal Practices"),
    WORKFORCE_DIVERSITY("Wikirate ESG Topics+Workforce Diversity"),
    SUSTAINABILITY_REPORTING("Wikirate ESG Topics+Sustainability Reporting"),
    ENERGY_INTENSITY("Wikirate ESG Topics+Energy Intensity"),
    WATER_USAGE("Wikirate ESG Topics+Water Usage"),
    COMPLIANCE_AND_CORRECTIVE_ACTION("Wikirate ESG Topics+Compliance and Corrective Action"),
    COLLECTIVE_BARGAINING("Wikirate ESG Topics+Collective Bargaining"),
    GENERAL_WASTE("Wikirate ESG Topics+General Waste"),
    JUST_TRANSITION("Wikirate ESG Topics+Just Transition"),
    LAND_USE("Wikirate ESG Topics+Land Use"),
    SUSTAINABILITY_GOVERNANCE_AND_OVERSIGHT("Wikirate ESG Topics+Sustainability Governance & Oversight"),
    MATERIAL_RECOVERY_AND_REUSE("Wikirate ESG Topics+Material Recovery & Reuse"),
    SUSTAINABILITY_GOALS_AND_TARGETS("Wikirate ESG Topics+Sustainability Goals & Targets"),
    CONSERVATION("Wikirate ESG Topics+Conservation"),
    POLLUTION("Wikirate ESG Topics+Pollution"),
    BIODIVERSITY_IMPACT_ASSESSMENT("Wikirate ESG Topics+Biodiversity Impact Assessment"),
    CHILD_LABOR("Wikirate ESG Topics+Child Labor"),
    LOBBYING_AND_POLITICAL_ENGAGEMENT("Wikirate ESG Topics+Lobbying & Political Engagement"),
    ESG_INTEGRATION_INTO_BUSINESS_STRATEGY("Wikirate ESG Topics+ESG Integration into Business Strategy"),
    DIGITAL_RESPONSIBILITY("Wikirate ESG Topics+Digital Responsibility"),
    WORKING_HOURS("Wikirate ESG Topics+Working Hours"),
    WATER_RISK_AND_SCARCITY_EXPOSURE("Wikirate ESG Topics+Water Risk & Scarcity Exposure"),
    COMMUNITY_ENGAGEMENT_PROGRAMS("Wikirate ESG Topics+Community Engagement Programs"),
    JOB_SECURITY("Wikirate ESG Topics+Job Security"),
    POLITICAL_CONTRIBUTIONS("Wikirate ESG Topics+Political Contributions"),
    ENERGY_SOURCING("Wikirate ESG Topics+Energy Sourcing"),
    IMPACT_ON_LOCAL_COMMUNITIES("Wikirate ESG Topics+Impact on Local Communities"),
    ORGANIC_AND_SUSTAINABLE_PRODUCTS("Wikirate ESG Topics+Organic and Sustainable Products"),
    RECYCLED_PRODUCTS("Wikirate ESG Topics+Recycled Products"),
    PAY_EQUITY_ANALYSIS("Wikirate ESG Topics+Pay Equity Analysis"),
    WORKPLACE_ACCIDENTS("Wikirate ESG Topics+Workplace Accidents"),
    LAND_USE_AND_DEGRADATION("Wikirate ESG Topics+Land Use & Degradation"),
    FORCED_LABOR("Wikirate ESG Topics+Forced Labor"),
    LOCAL_SOURCING("Wikirate ESG Topics+Local Sourcing"),
    CRISIS_RESPONSE_AND_RESILIENCE("Wikirate ESG Topics+Crisis Response & Resilience"),
    HAZARDOUS_WASTE("Wikirate ESG Topics+Hazardous Waste"),
    HABITAT_PROTECTION("Wikirate ESG Topics+Habitat Protection"),
    WATER_POLLUTION_AND_EFFLUENTS("Wikirate ESG Topics+Water Pollution & Effluents"),
    CORPORATE_TAX_TRANSPARENCY("Wikirate ESG Topics+Corporate Tax Transparency"),
    BRIBERY_AND_CORRUPTION_PREVENTION("Wikirate ESG Topics+Bribery & Corruption Prevention"),
    WHISTLEBLOWING_MECHANISMS("Wikirate ESG Topics+Whistleblowing Mechanisms"),
    ESG_RISK_INTEGRATION("Wikirate ESG Topics+ESG Risk Integration"),
    ANTI_DISCRIMINATION_MEASURES("Wikirate ESG Topics+Anti-Discrimination Measures"),
    BOARD_COMPOSITION_AND_INDEPENDENCE("Wikirate ESG Topics+Board Composition & Independence"),
    TAX_TRANSPARENCY("Wikirate ESG Topics+Tax Transparency"),
    WASTEWATER_DISCHARGE("Wikirate ESG Topics+Wastewater Discharge"),
    NON_COMPLIANCE_AND_SANCTIONS("Wikirate ESG Topics+Non-compliance and Sanctions"),
    SUSTAINABLE_FORESTRY("Wikirate ESG Topics+Sustainable Forestry"),
    CONSUMER_RIGHTS("Wikirate ESG Topics+Consumer Rights"),
    FOOD_WASTE("Wikirate ESG Topics+Food Waste"),
    EXECUTIVE_PAY_AND_BONUSES("Wikirate ESG Topics+Executive Pay & Bonuses"),
    ANNUAL_REPORTING("Wikirate ESG Topics+Annual Reporting"),
    SUPPLIER_DIVERSITY("Wikirate ESG Topics+Supplier Diversity"),
    DATA_PROTECTION_AND_PRIVACY("Wikirate ESG Topics+Data Protection & Privacy"),
    AIR_POLLUTION("Wikirate ESG Topics+Air Pollution"),
    DEFORESTATION("Wikirate ESG Topics+Deforestation"),
    SAFETY_TRAINING("Wikirate ESG Topics+Safety Training"),
    SOCIAL_DIALOGUE_AND_STAKEHOLDER_ENGAGEMENT("Wikirate ESG Topics+Social Dialogue & Stakeholder Engagement"),
    PRODUCT_LIFECYCLE_MANAGEMENT("Wikirate ESG Topics+Product Lifecycle Management"),
    CIRCULAR_SUPPLY_CHAINS("Wikirate ESG Topics+Circular Supply Chains"),
    DISCRIMINATION_AND_HARASSMENT("Wikirate ESG Topics+Discrimination and Harassment"),
    ENTERPRISE_RISK_MANAGEMENT("Wikirate ESG Topics+Enterprise Risk Management"),
    EFFECTIVE_TAX_RATE_DISCLOSURE("Wikirate ESG Topics+Effective Tax Rate Disclosure"),
    FUEL_CONSUMPTION("Wikirate ESG Topics+Fuel Consumption"),
    INTEGRATED_REPORTING("Wikirate ESG Topics+Integrated Reporting"),
    BIODIVERSITY_AGREEMENTS("Wikirate ESG Topics+Biodiversity Agreements"),
    SUSTAINABLE_INVESTMENT("Wikirate ESG Topics+Sustainable Investment"),
    LOBBYING_EXPENDITURES("Wikirate ESG Topics+Lobbying Expenditures"),
    HEALTH_RISK_ASSESSMENTS("Wikirate ESG Topics+Health Risk Assessments"),
    NATURE_BASED_SOLUTIONS("Wikirate ESG Topics+Nature-based Solutions"),
    DIGITAL_RIGHTS("Wikirate ESG Topics+Digital Rights"),
    RESKILLING_AND_WORKFORCE_TRANSITION("Wikirate ESG Topics+Reskilling & Workforce Transition"),
    MATERIALITY_ASSESSMENT("Wikirate ESG Topics+Materiality Assessment"),
    LAND_DEGRADATION("Wikirate ESG Topics+Land Degradation"),
    CLIMATE_RISK_MANAGEMENT("Wikirate ESG Topics+Climate Risk Management"),
    TAX_POLICY_AND_STRATEGY("Wikirate ESG Topics+Tax Policy & Strategy"),
    ETHICAL_USE_OF_TECHNOLOGY("Wikirate ESG Topics+Ethical Use of Technology"),
    FAIR_MARKETING_AND_CONSUMER_INFORMATION("Wikirate ESG Topics+Fair Marketing & Consumer Information"),
    ETHNIC_AND_RACIAL_EQUITY("Wikirate ESG Topics+Ethnic & Racial Equity"),
    MENTAL_HEALTH_POLICIES("Wikirate ESG Topics+Mental Health Policies"),
    USE_OF_CARBON_OFFSETS("Wikirate ESG Topics+Use of Carbon Offsets"),
    LAND_CONVERSION_FOR_AGRICULTURE("Wikirate ESG Topics+Land Conversion for Agriculture"),
    LAND_REHABILITATION_AND_RESTORATION("Wikirate ESG Topics+Land Rehabilitation & Restoration"),
    CODE_OF_ETHICS("Wikirate ESG Topics+Code of Ethics"),
    EMERGENCY_PREPAREDNESS("Wikirate ESG Topics+Emergency Preparedness"),
    CONFLICT_AFFECTED_AREAS("Wikirate ESG Topics+Conflict-Affected Areas"),
    LGBT_INCLUSION("Wikirate ESG Topics+LGBT Inclusion"),
    EQUITY_IN_CLIMATE_POLICIES("Wikirate ESG Topics+Equity in Climate Policies"),
    POLICY_INFLUENCE_STRATEGIES("Wikirate ESG Topics+Policy Influence Strategies"),
    COUNTRY_BY_COUNTRY_REPORTING("Wikirate ESG Topics+Country-by-Country Reporting"),
    SOCIAL_INVESTMENT("Wikirate ESG Topics+Social Investment"),
    KNOWLEDGE_SHARING("Wikirate ESG Topics+Knowledge Sharing"),
    INDIGENOUS_PEOPLES_RIGHTS("Wikirate ESG Topics+Indigenous Peoples Rights"),
    PARENTAL_POLICIES("Wikirate ESG Topics+Parental Policies"),
    INCLUSION_POLICIES("Wikirate ESG Topics+Inclusion Policies"),
    BOARD_DIVERSITY("Wikirate ESG Topics+Board Diversity"),
    DISABILITY_INCLUSION("Wikirate ESG Topics+Disability Inclusion"),
    SOIL_CONTAMINATION("Wikirate ESG Topics+Soil Contamination"),
    INDUSTRIAL_EMISSIONS("Wikirate ESG Topics+Industrial Emissions"),
    REPUTATIONAL_RISK("Wikirate ESG Topics+Reputational Risk"),
    CYBERSECURITY_RISK("Wikirate ESG Topics+Cybersecurity Risk"),
    COMMUNITY_EDUCATION_INITIATIVES("Wikirate ESG Topics+Community Education Initiatives"),
    COMMUNITY_IMPACT_AND_SUPPORT_PROGRAMS("Wikirate ESG Topics+Community Impact & Support Programs"),
    MONOCULTURE("Wikirate ESG Topics+Monoculture"),
    TERMINATION_AND_DISMISSAL_PRACTICES("Wikirate ESG Topics+Termination & Dismissal Practices"),
    INCLUSION_IN_TRANSITION_PLANNING("Wikirate ESG Topics+Inclusion in Transition Planning"),
    PHILANTHROPY("Wikirate ESG Topics+Philanthropy"),
    PRODUCT_SAFETY("Wikirate ESG Topics+Product Safety"),
    TEMPORARY_WORK("Wikirate ESG Topics+Temporary Work"),
    GENETICALLY_MODIFIED_ORGANISMS_GMO("Wikirate ESG Topics+Genetically Modified Organisms (GMO)"),
    CONSUMER_GRIEVANCE_MECHANISMS("Wikirate ESG Topics+Consumer Grievance Mechanisms"),
    MINING_IMPACTS_ON_LAND("Wikirate ESG Topics+Mining Impacts on Land"),
    URBAN_DEVELOPMENT_IMPACT("Wikirate ESG Topics+Urban Development Impact"),
    TAX_AVOIDANCE_PRACTICES("Wikirate ESG Topics+Tax Avoidance Practices"),
    AI_ETHICS_AND_GOVERNANCE("Wikirate ESG Topics+AI Ethics & Governance"),
    NOISE_POLLUTION("Wikirate ESG Topics+Noise Pollution"),
    ELECTRONIC_WASTE_EWASTE("Wikirate ESG Topics+Electronic Waste (E-Waste)"),
    DESERTIFICATION("Wikirate ESG Topics+Desertification"),
    ALGORITHMIC_BIAS_AND_FAIRNESS("Wikirate ESG Topics+Algorithmic Bias & Fairness"),
    CYBERSECURITY_RISK_AND_RESILIENCE("Wikirate ESG Topics+Cybersecurity Risk & Resilience"),
    DATA_ETHICS("Wikirate ESG Topics+Data Ethics"),
    STUDENT_ENGAGEMENT("Wikirate ESG Topics+Student Engagement"),
    PERSONAL_PROTECTIVE_EQUIPMENT("Wikirate ESG Topics+Personal Protective Equipment"),
    UNKNOWN("");

    private final String value;

    private WikirateTopic(String value) {
        this.value = value;
    }

    public String value() {
        return this.value;
    }

    public static WikirateTopic getWikirateTopic(String topic) {
        for (WikirateTopic wikirateTopic : values()) {
            if (wikirateTopic.value().equals(topic)) {
                return wikirateTopic;
            }
        }

        return UNKNOWN;
    }
}
